import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Layout } from "@/app/components/layout";
import ThemeClient from "@/app/components/themes/ThemeClient";
import { getServerSession } from "next-auth";
import SessionProvider from "@/app/components/auth/SessionProvider";
import { redirect } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();

  if (!session || !session.user) {
    redirect("api/auth/signin");
  }

  return (
    <html lang="en">
      <meta
        name="google-site-verification"
        content="VCymJhnZunDnSL0DkrcDf_qu1RlyfOvalXaUbdkvsEU"
      />
      <body className={inter.className}>
        <SessionProvider session={session}>
          <ThemeClient>
            <Layout>{children}</Layout>
          </ThemeClient>
        </SessionProvider>
      </body>
    </html>
  );
}
